
import React from 'react';
export const ingredientslist = [
    { value: 'Almonds', label: 'Almonds' },
    { value: 'All-purpose flour', label: 'All-purpose flour' },
    { value: 'Apple cider vinegar', label: 'Apple cider vinegar' },
    { value: 'Apples', label: 'Apples' },
    { value: 'Avocados', label: 'Avocados' },
    { value: 'Bagel', label: 'Bagel' },
    { value: 'Bacon', label: 'Bacon' },
    { value: 'Bananas', label: 'Bananas' },
    { value: 'Balsamic vinegar', label: 'Balsamic vinegar' },
    { value: 'Barley', label: 'Barley' },
    { value: 'Basil', label: 'Basil' },
    { value: 'Bay leaves', label: 'Bay leaves' },
    { value: 'Beef', label: 'Beef' },
    { value: 'Berries', label: 'Berries' },
    { value: 'Bell peppers', label: 'Bell peppers' },
    { value: 'Biscuits', label: 'Biscuits' },
    { value: 'Black beans', label: 'Black beans' },
    { value: 'Black pepper', label: 'Black pepper' },
    { value: 'Blueberries', label: 'Blueberries' },
    { value: 'Bread', label: 'Bread' },
    { value: 'Broth', label: 'Broth' },
    { value: 'Brussels sprouts', label: 'Brussels sprouts' },
    { value: 'Butter', label: 'Butter' },
    { value: 'Cabbage', label: 'Cabbage' },
    { value: 'Canola oil', label: 'Canola oil' },
    { value: 'Carrots', label: 'Carrots' },
    { value: 'Canned beans (black beans, chickpeas, kidney beans)', label: 'Canned beans (black beans, chickpeas, kidney beans)' },
    { value: 'Canned coconut milk', label: 'Canned coconut milk' },
    { value: 'Canned tuna', label: 'Canned tuna' },
    { value: 'Cheese', label: 'Cheese' },
    { value: 'Chicken', label: 'Chicken' },
    { value: 'Chicken thighs', label: 'Chicken thighs' },
    { value: 'Chickpeas', label: 'Chickpeas' },
    { value: 'Chili powder', label: 'Chili powder' },
    { value: 'Cilantro', label: 'Cilantro' },
    { value: 'Cinnamon', label: 'Cinnamon' },
    { value: 'Cocoa powder', label: 'Cocoa powder' },
    { value: 'Coconut flakes (shredded)', label: 'Coconut flakes (shredded)' },
    { value: 'Coconut oil', label: 'Coconut oil' },
    { value: 'Coleslaw', label: 'Coleslaw' },
    { value: 'Couscous', label: 'Couscous' },
    { value: 'Cream cheese', label: 'Cream cheese' },
    { value: 'Cream', label: 'Cream' },
    { value: 'Cucumber', label: 'Cucumber' },
    { value: 'Curry powder', label: 'Curry powder' },
    { value: 'Dill', label: 'Dill' },
    { value: 'Eggplant', label: 'Eggplant' },
    { value: 'Eggs', label: 'Eggs' },
    { value: 'Extra virgin olive oil', label: 'Extra virgin olive oil' },
    { value: 'Feta cheese', label: 'Feta cheese' },
    { value: 'Garlic', label: 'Garlic' },
    { value: 'Ginger', label: 'Ginger' },
    { value: 'Grapes', label: 'Grapes' },
    { value: 'Ground beef', label: 'Ground beef' },
    { value: 'Heavy cream', label: 'Heavy cream' },
    { value: 'Herbs de Provence', label: 'Herbs de Provence' },
    { value: 'Hot sauce', label: 'Hot sauce' },
    { value: 'Honey', label: 'Honey' },
    { value: 'Kale', label: 'Kale' },
    { value: 'Ketchup', label: 'Ketchup' },
    { value: 'Lamb', label: 'Lamb' },
    { value: 'Lentils', label: 'Lentils' },
    { value: 'Lemon', label: 'Lemon' },
    { value: 'Lettuce', label: 'Lettuce' },
    { value: 'Lime', label: 'Lime' },
    { value: 'Maple syrup', label: 'Maple syrup' },
    { value: 'Mango', label: 'Mango' },
    { value: 'Milk', label: 'Milk' },
    { value: 'Mustard', label: 'Mustard' },
    { value: 'Mushrooms', label: 'Mushrooms' },
    { value: 'Nutmeg', label: 'Nutmeg' },
    { value: 'Oats', label: 'Oats' },
    { value: 'Olive oil', label: 'Olive oil' },
    { value: 'Onions', label: 'Onions' },
    { value: 'Oregano', label: 'Oregano' },
    { value: 'Paprika', label: 'Paprika' },
    { value: 'Parsley', label: 'Parsley' },
    { value: 'Peaches', label: 'Peaches' },
    { value: 'Peanut butter', label: 'Peanut butter' },
    { value: 'Pecans', label: 'Pecans' },
    { value: 'Pineapple', label: 'Pineapple' },
    { value: 'Pistachios', label: 'Pistachios' },
    { value: 'Potatoes', label: 'Potatoes' },
    { value: 'Pork', label: 'Pork' },
    { value: 'Prawns', label: 'Prawns' },
    { value: 'Pasta', label: 'Pasta' },
    { value: 'Pasta Sauce', label: 'Pasta Sauce'},
    { value: 'Rasberries', label: 'Rasberries' },
    { value: 'Rice vinegar', label: 'Rice vinegar' },
    { value: 'Rice', label: 'Rice' },
    { value: 'Ricotta cheese', label: 'Ricotta cheese' },
    { value: 'Red wine vinegar', label: 'Red wine vinegar' },
    { value: 'Rosemary', label: 'Rosemary' },
    { value: 'Sage', label: 'Sage' },
    { value: 'Salmon', label: 'Salmon' },
    { value: 'Salt', label: 'Salt' },
    { value: 'Sesame oil', label: 'Sesame oil' },
    { value: 'Seaweed', label: 'Seaweed' },
    { value: 'Shrimp', label: 'Shrimp' },
    { value: 'Soy sauce', label: 'Soy sauce' },
    { value: 'Sriracha', label: 'Sriracha' },
    { value: 'Spinach', label: 'Spinach' },
    { value: 'Sugar', label: 'Sugar' },
    { value: 'Sweet potatoes', label: 'Sweet potatoes' },
    { value: 'Tahini', label: 'Tahini' },
    { value: 'Thyme', label: 'Thyme' },
    { value: 'Tomatoes', label: 'Tomatoes' },
    { value: 'Tofu', label: 'Tofu' },
    { value: 'Tuna', label: 'Tuna' },
    { value: 'Turkey breast', label: 'Turkey breast' },
    { value: 'Vanilla extract', label: 'Vanilla extract' },
    { value: 'Walnuts', label: 'Walnuts' },
    { value: 'Whole wheat flour', label: 'Whole wheat flour' },
    { value: 'Zucchini', label: 'Zucchini' }

];



