// recipesData.js

export const recipesData = {
    vegetarian: [
      {
        title: "Caprese Avocado Toast",
        ingredients: [
          "2 slices whole-grain bread (or gluten-free option)",
          "½ avocado, mashed",
          "4 cherry tomatoes, halved",
          "2 tbsp fresh mozzarella, sliced",
          "1 tsp balsamic glaze",
          "½ tsp black pepper",
          "Fresh basil leaves",
        ],
        instructions: [
          "Toast the bread until crispy.",
          "Spread mashed avocado on each slice.",
          "Top with cherry tomatoes and fresh mozzarella.",
          "Drizzle with balsamic glaze and sprinkle with black pepper.",
          "Garnish with basil leaves and serve.",
        ],
      },
      {
        title: "Creamy Spinach & Mushroom Pasta",
        ingredients: [
          "8 oz pasta (penne or spaghetti)",
          "1 tbsp olive oil",
          "1 cup mushrooms, sliced",
          "2 cups fresh spinach",
          "2 cloves garlic, minced",
          "1 cup heavy cream (or coconut cream for dairy-free)",
          "½ cup grated Parmesan cheese",
          "½ tsp salt",
          "½ tsp black pepper",
        ],
        instructions: [
          "Cook pasta according to package instructions.",
          "Heat olive oil in a pan and sauté mushrooms and garlic for 5 minutes.",
          "Add spinach and cook until wilted.",
          "Pour in heavy cream and let it simmer for 2 minutes.",
          "Stir in Parmesan cheese, salt, and black pepper.",
          "Toss with pasta and serve.",
        ],
      },
      {
        title: "Chickpea & Vegetable Curry",
        ingredients: [
          "1 can (15 oz) chickpeas, drained and rinsed",
          "1 cup coconut milk",
          "1 bell pepper, diced",
          "1 carrot, sliced",
          "1 small potato, diced",
          "2 cloves garlic, minced",
          "1 tsp curry powder",
          "½ tsp cumin",
          "½ tsp salt",
          "1 tbsp olive oil",
        ],
        instructions: [
          "Heat olive oil in a pan and sauté garlic for 1 minute.",
          "Add bell pepper, carrot, and potato, and cook for 5 minutes.",
          "Stir in chickpeas, curry powder, cumin, and salt.",
          "Pour in coconut milk and let it simmer for 15 minutes.",
          "Serve with rice or naan.",
        ],
      },
      {
        title: "Veggie Tacos with Black Beans",
        ingredients: [
          "4 small corn tortillas",
          "1 can (15 oz) black beans, drained and rinsed",
          "1 avocado, sliced",
          "½ cup shredded lettuce",
          "½ cup salsa",
          "½ tsp chili powder",
          "½ tsp cumin",
          "1 tbsp olive oil",
        ],
        instructions: [
          "Heat olive oil in a pan and sauté black beans with chili powder and cumin for 5 minutes.",
          "Warm tortillas in a dry pan for 1 minute per side.",
          "Fill tortillas with black beans, avocado slices, lettuce, and salsa.",
          "Serve and enjoy!",
        ],
      },
      {
        title: "Mediterranean Quinoa Salad",
        ingredients: [
          "1 cup cooked quinoa",
          "½ cucumber, diced",
          "½ cup cherry tomatoes, halved",
          "¼ cup feta cheese, crumbled",
          "2 tbsp olive oil",
          "Juice of ½ lemon",
          "½ tsp salt",
          "½ tsp black pepper",
        ],
        instructions: [
          "In a bowl, combine quinoa, cucumber, cherry tomatoes, and feta cheese.",
          "Drizzle with olive oil and lemon juice.",
          "Season with salt and black pepper.",
          "Toss everything together and serve chilled.",
        ],
      },
    ],
  
    dairyFree: [
      {
        title: "Coconut Curry Chicken",
        ingredients: [
          "1 lb chicken breast, diced",
          "1 can (13.5 oz) coconut milk",
          "1 onion, chopped",
          "2 cloves garlic, minced",
          "1 tbsp curry powder",
          "1 tsp turmeric",
          "1 tsp cumin",
          "1 tbsp olive oil",
          "Salt and pepper to taste",
          "1 cup chopped bell peppers",
          "1 cup spinach (optional)",
        ],
        instructions: [
          "Heat olive oil in a pan over medium heat.",
          "Add onion and garlic, sauté until fragrant.",
          "Add chicken and cook until browned.",
          "Stir in curry powder, turmeric, and cumin.",
          "Pour in coconut milk and bring to a simmer.",
          "Add bell peppers and spinach, cook for 5 more minutes.",
          "Season with salt and pepper. Serve with rice.",
        ],
      },
      {
        title: "Dairy-Free Banana Pancakes",
        ingredients: [
          "2 ripe bananas, mashed",
          "2 eggs",
          "½ cup oat flour (or blended oats)",
          "1 tsp baking powder",
          "½ tsp cinnamon",
          "1 tsp vanilla extract",
        ],
        instructions: [
          "In a bowl, mix mashed bananas, eggs, oat flour, baking powder, cinnamon, and vanilla.",
          "Heat a non-stick pan over medium heat.",
          "Pour small amounts of batter into the pan.",
          "Cook for 2-3 minutes per side until golden brown.",
          "Serve with honey or fresh fruit.",
        ],
      },
      {
        title: "Dairy-Free Avocado Pasta",
        ingredients: [
          "1 avocado",
          "1 garlic clove",
          "½ cup fresh basil",
          "2 tbsp olive oil",
          "Juice of 1 lemon",
          "Salt and pepper to taste",
          "8 oz cooked pasta (gluten-free if needed)",
        ],
        instructions: [
          "Blend avocado, garlic, basil, olive oil, lemon juice, salt, and pepper into a creamy sauce.",
          "Toss the sauce with warm pasta.",
          "Serve with cherry tomatoes or grilled chicken.",
        ],
      },
      {
        title: "Dairy-Free Chocolate Chia Pudding",
        ingredients: [
          "1 cup almond milk (or oat milk)",
          "¼ cup chia seeds",
          "2 tbsp cocoa powder",
          "1 tbsp maple syrup (or honey)",
          "½ tsp vanilla extract",
        ],
        instructions: [
          "Whisk all ingredients in a bowl.",
          "Let sit for 5 minutes, then stir again to prevent clumping.",
          "Refrigerate for at least 2 hours or overnight.",
          "Serve with fresh fruit or nuts.",
        ],
      },
      {
        title: "Vegan Lentil Soup",
        ingredients: [
          "1 cup dried lentils",
          "4 cups vegetable broth",
          "1 onion, chopped",
          "2 carrots, diced",
          "2 cloves garlic, minced",
          "1 tsp cumin",
          "1 tsp paprika",
          "Salt and pepper to taste",
          "1 tbsp olive oil",
        ],
        instructions: [
          "Heat olive oil in a pot over medium heat.",
          "Sauté onion, carrots, and garlic until soft.",
          "Add cumin, paprika, lentils, and vegetable broth.",
          "Bring to a boil, then simmer for 25-30 minutes.",
          "Blend for a creamy texture or serve chunky.",
        ],
      },
    ],
  
    vegan: [
      {
        title: "Chickpea Stir-Fry",
        ingredients: [
          "1 can (15 oz) chickpeas, drained and rinsed",
          "1 bell pepper, sliced",
          "1 zucchini, sliced",
          "1 cup broccoli florets",
          "2 tbsp soy sauce (or tamari for gluten-free)",
          "1 tbsp olive oil",
          "1 tsp garlic powder",
          "½ tsp red pepper flakes (optional)",
          "1 tbsp sesame seeds",
        ],
        instructions: [
          "Heat olive oil in a pan over medium heat.",
          "Add chickpeas, garlic powder, and red pepper flakes, sauté for 3 minutes.",
          "Add bell pepper, zucchini, and broccoli, stirring occasionally.",
          "Pour in soy sauce and cook for another 5 minutes.",
          "Garnish with sesame seeds and serve with rice or quinoa.",
        ],
      },
      {
        title: "Vegan Lentil Soup",
        ingredients: [
          "1 cup dried lentils",
          "4 cups vegetable broth",
          "1 onion, chopped",
          "2 carrots, diced",
          "2 cloves garlic, minced",
          "1 tsp cumin",
          "1 tsp paprika",
          "1 tbsp olive oil",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Heat olive oil in a pot over medium heat.",
          "Sauté onion, carrots, and garlic until soft.",
          "Add cumin, paprika, lentils, and vegetable broth.",
          "Bring to a boil, then simmer for 25-30 minutes.",
          "Blend for a creamy texture or serve chunky.",
        ],
      },
      {
        title: "Avocado Toast with Hummus & Tomato",
        ingredients: [
          "2 slices whole-grain bread (or gluten-free option)",
          "½ avocado, mashed",
          "2 tbsp hummus",
          "1 small tomato, sliced",
          "½ tsp black pepper",
          "½ tsp red pepper flakes (optional)",
        ],
        instructions: [
          "Toast the bread until crispy.",
          "Spread hummus on one slice and mashed avocado on the other.",
          "Top with tomato slices, black pepper, and red pepper flakes.",
          "Enjoy as a quick breakfast or snack.",
        ],
      },
      {
        title: "Vegan Chocolate Chia Pudding",
        ingredients: [
          "1 cup almond milk (or oat milk)",
          "¼ cup chia seeds",
          "2 tbsp cocoa powder",
          "1 tbsp maple syrup",
          "½ tsp vanilla extract",
        ],
        instructions: [
          "Mix all ingredients in a bowl until well combined.",
          "Let sit for 5 minutes, then stir again.",
          "Cover and refrigerate for at least 2 hours or overnight.",
          "Serve with fresh fruit or nuts.",
        ],
      },
      {
        title: "Sweet Potato & Black Bean Tacos",
        ingredients: [
          "1 medium sweet potato, diced",
          "1 can (15 oz) black beans, drained and rinsed",
          "1 tsp chili powder",
          "1 tsp cumin",
          "½ tsp garlic powder",
          "1 tbsp olive oil",
          "4 small corn tortillas",
          "1 avocado, sliced",
          "½ cup salsa",
          "Fresh cilantro (optional)",
        ],
        instructions: [
          "Preheat oven to 400°F (200°C).",
          "Toss diced sweet potatoes with olive oil, chili powder, cumin, and garlic powder. Roast for 20 minutes.",
          "Heat black beans in a small pan for 5 minutes.",
          "Warm tortillas and fill with sweet potatoes, black beans, avocado, and salsa.",
          "Garnish with cilantro and enjoy!",
        ],
      },
    ],
  
    glutenFree: [
      {
        title: "Quinoa & Vegetable Stir-Fry",
        ingredients: [
          "1 cup cooked quinoa",
          "1 zucchini, chopped",
          "1 bell pepper, sliced",
          "1 carrot, julienned",
          "1 cup broccoli florets",
          "2 tbsp olive oil",
          "2 tbsp tamari (gluten-free soy sauce)",
          "1 tsp garlic powder",
          "½ tsp red pepper flakes (optional)",
          "1 tbsp sesame seeds",
        ],
        instructions: [
          "Heat olive oil in a pan over medium heat.",
          "Add zucchini, bell pepper, carrot, and broccoli, and sauté for 5 minutes.",
          "Stir in tamari, garlic powder, and red pepper flakes.",
          "Add quinoa and mix well, cooking for another 3 minutes.",
          "Garnish with sesame seeds and serve.",
        ],
      },
      {
        title: "Gluten-Free Banana Pancakes",
        ingredients: [
          "2 ripe bananas, mashed",
          "2 eggs",
          "½ cup gluten-free oat flour (or blended oats)",
          "1 tsp vanilla extract",
          "½ tsp cinnamon",
          "½ tsp baking powder",
        ],
        instructions: [
          "In a bowl, mix mashed bananas, eggs, vanilla, cinnamon, and baking powder.",
          "Stir in oat flour until smooth.",
          "Heat a non-stick pan over medium heat and pour small pancake circles.",
          "Cook for 2-3 minutes per side.",
          "Serve with maple syrup or fresh fruit.",
        ],
      },
      {
        title: "Baked Lemon Garlic Salmon",
        ingredients: [
          "2 salmon fillets",
          "1 tbsp olive oil",
          "Juice of 1 lemon",
          "1 tsp garlic powder",
          "½ tsp black pepper",
          "1 tsp dried oregano",
        ],
        instructions: [
          "Preheat oven to 400°F (200°C).",
          "Place salmon on a baking sheet and drizzle with olive oil and lemon juice.",
          "Sprinkle garlic powder, black pepper, and oregano on top.",
          "Bake for 12-15 minutes.",
          "Serve with roasted vegetables or quinoa.",
        ],
      },
      {
        title: "Chickpea & Avocado Salad",
        ingredients: [
          "1 can (15 oz) chickpeas, drained and rinsed",
          "1 avocado, diced",
          "½ cup cherry tomatoes, halved",
          "¼ red onion, chopped",
          "2 tbsp olive oil",
          "Juice of ½ lemon",
          "½ tsp salt",
          "½ tsp black pepper",
        ],
        instructions: [
          "In a bowl, mix chickpeas, avocado, cherry tomatoes, and red onion.",
          "Drizzle with olive oil and lemon juice.",
          "Season with salt and black pepper.",
          "Toss everything together and serve.",
        ],
      },
      {
        title: "Flourless Chocolate Mug Cake",
        ingredients: [
          "1 ripe banana, mashed",
          "1 egg",
          "2 tbsp cocoa powder",
          "½ tsp baking powder",
          "1 tbsp maple syrup (optional)",
        ],
        instructions: [
          "Mix all ingredients in a microwave-safe mug until smooth.",
          "Microwave for 60-90 seconds.",
          "Let cool for a minute, then enjoy!",
        ],
      },
    ],
  
    none: [
      {
        title: "Classic Spaghetti Bolognese",
        ingredients: [
          "1 lb ground beef (or pork)",
          "1 small onion, chopped",
          "2 cloves garlic, minced",
          "1 can (28 oz) crushed tomatoes",
          "1 tbsp tomato paste",
          "½ tsp salt",
          "½ tsp black pepper",
          "1 tsp dried oregano",
          "1 tsp dried basil",
          "12 oz spaghetti",
          "2 tbsp olive oil",
          "Grated Parmesan cheese (for topping)",
        ],
        instructions: [
          "Heat olive oil in a pan and sauté onion and garlic until fragrant.",
          "Add ground beef and cook until browned.",
          "Stir in crushed tomatoes, tomato paste, salt, pepper, oregano, and basil. Simmer for 20 minutes.",
          "Cook spaghetti according to package instructions, then drain.",
          "Serve pasta topped with Bolognese sauce and Parmesan cheese.",
        ],
      },
      {
        title: "Classic Cheeseburger",
        ingredients: [
          "1 lb ground beef",
          "½ tsp salt",
          "½ tsp black pepper",
          "½ tsp garlic powder",
          "4 hamburger buns",
          "4 slices cheddar cheese",
          "Lettuce, tomato, and onion slices",
          "Ketchup and mustard",
        ],
        instructions: [
          "Preheat grill or pan to medium-high heat.",
          "Mix ground beef with salt, pepper, and garlic powder, then shape into 4 patties.",
          "Cook patties for 3-4 minutes per side, adding cheese in the last minute.",
          "Toast buns slightly, then assemble burgers with lettuce, tomato, onion, ketchup, and mustard.",
        ],
      },
      {
        title: "Chicken Stir-Fry",
        ingredients: [
          "2 boneless, skinless chicken breasts, sliced",
          "1 cup broccoli florets",
          "1 bell pepper, sliced",
          "1 carrot, julienned",
          "2 tbsp soy sauce",
          "1 tbsp honey",
          "1 tsp sesame oil",
          "1 tsp garlic, minced",
          "2 tbsp vegetable oil",
          "Cooked rice (for serving)",
        ],
        instructions: [
          "Heat vegetable oil in a pan over medium-high heat.",
          "Add chicken and cook for 5-7 minutes until golden.",
          "Add broccoli, bell pepper, and carrot, cooking for another 3 minutes.",
          "Stir in soy sauce, honey, sesame oil, and garlic. Cook for 2 more minutes.",
          "Serve over rice.",
        ],
      },
      {
        title: "Margherita Pizza",
        ingredients: [
          "1 pizza dough",
          "½ cup tomato sauce",
          "1 cup fresh mozzarella, sliced",
          "1 tbsp olive oil",
          "1 tsp dried oregano",
          "Fresh basil leaves",
        ],
        instructions: [
          "Preheat oven to 475°F (245°C).",
          "Roll out pizza dough and place on a baking sheet.",
          "Spread tomato sauce evenly and top with mozzarella slices.",
          "Drizzle with olive oil and sprinkle with oregano.",
          "Bake for 10-12 minutes until crust is golden.",
          "Top with fresh basil and serve.",
        ],
      },
      {
        title: "Chocolate Chip Cookies",
        ingredients: [
          "1 cup butter, softened",
          "¾ cup sugar",
          "¾ cup brown sugar",
          "2 eggs",
          "1 tsp vanilla extract",
          "2 ¼ cups all-purpose flour",
          "1 tsp baking soda",
          "½ tsp salt",
          "2 cups chocolate chips",
        ],
        instructions: [
          "Preheat oven to 350°F (175°C).",
          "Cream butter, sugar, and brown sugar together.",
          "Mix in eggs and vanilla extract.",
          "Stir in flour, baking soda, and salt until combined.",
          "Fold in chocolate chips.",
          "Drop spoonfuls of dough onto a baking sheet and bake for 10-12 minutes.",
        ],
      },
    ],
  };
  